############################################################
## Pipeline template that publish a VM Image             ###
##    to an Azure Image Library                          ###
#  - All gallery related variables                       ###
#      are readed from variable group                    ###
#                                                        ###
############################################################

parameters:
  - name: job_id
    type: string
    default: 'generate_image'
  
  - name: image_type
    type: string

  - name: agent_pool
    type: object

  - name: variable_group_name
    type: string

  - name: repository_ref
    type: string
    default: 'self'

  - name: managed_image_name
    type: string
    displayName: 'Name of the Image Definition in the Azure Compute Gallery.'

  - name: source_managed_image
    type: string
    displayName: 'Resource Id of the VM Image to be published.'

  - name: azureServiceConnection
    type: string
    displayName: 'Name of the AzureRM service connection used to publish.'
  
  - name: replica_count
    type: number
    default: 1
    displayName: 'The default number of replicas to be created per region.'
    

jobs:
- job: ${{ parameters.job_id }}
  displayName: Image Publish (${{ parameters.image_type }})
  timeoutInMinutes: 600
  cancelTimeoutInMinutes: 30
  pool: ${{ parameters.agent_pool }}
  variables:
  - group: ${{ parameters.variable_group_name }}

  steps:
    - checkout: ${{ parameters.repository_ref }}
      fetchTags: true
      persistCredentials: true

    - pwsh: |
        $imageFullName = "${{ parameters.source_managed_image }}" -split '/' | Select-Object -Last 1
        $buildVersion = $imageFullName -split '_' | Select-Object -Last 1
        $publishVersion = $buildVersion -replace '(\d+\.\d+\.\d+).*', '$1'
        Write-Host "Image version that will be used: $buildVersion"
        Write-Host "Image version that will be published: $publishVersion"
        Write-Host "##vso[task.setvariable variable=PublishVersion;]$publishVersion"
        Write-Host "##vso[build.updatebuildnumber]$buildVersion"
      name: setvar
      displayName: 'devops: set build number'

    - task: AzureCLI@2
      displayName: 'az: publish image'
      inputs:
        azureSubscription: '${{ parameters.azureServiceConnection }}'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $params = New-Object System.Collections.ArrayList
          [void]$params.Add("--gallery-name"); [void]$params.Add("$(IMAGE_GALLERY_NAME)");
          [void]$params.Add("--resource-group"); [void]$params.Add("$(IMAGE_GALLERY_RESOURCE_GROUP)");
          [void]$params.Add("--gallery-image-definition"); [void]$params.Add("${{ parameters.managed_image_name }}");
          [void]$params.Add("--gallery-image-version"); [void]$params.Add("$(PublishVersion)");
          [void]$params.Add("--subscription"); [void]$params.Add("$(IMAGE_GALLERY_SUBSCRIPTION_ID)");
          [void]$params.Add("--replica-count"); [void]$params.Add(${{ parameters.replica_count }});
          [void]$params.Add("--storage-account-type"); [void]$params.Add("$(IMAGE_GALLERY_REPLICATION)");
          [void]$params.Add("--managed-image"); [void]$params.Add("${{ parameters.source_managed_image }}");
          [void]$params.Add("--tags"); [void]$params.Add("SourceImage=${{ parameters.source_managed_image }}");
          ##[void]$params.Add("--no-wait")

          Write-Host "Publishing image with parameters [$($params | ConvertTo-Json)]"
          az sig image-version create @params --target-regions "West Europe" eastus2

    - script: |
        git config --global user.name "publisher"
        git tag $(PublishVersion)
        git push origin $(PublishVersion)
      displayName: 'git: set tag'
      condition: eq(variables['Build.SourceBranchName'], 'xtratus')
      continueOnError: false
