trigger: none
pr: none
resources:
  pipelines:
    - pipeline: build
      source: selfhosted_ubuntu_22.04-build
      trigger:
        branches:
          include:
            - xtratus
            - feature/*
            - feat/*
            - hotfix/*
            - fix/*
          exclude:
            - main

stages:
  - stage: image_publish
    variables:
      - name: managed_image_name
        value: "SelfHosted_Ubuntu2204"
      - name: managed_image_name_full
        value: "${{ lower(variables.managed_image_name) }}_$(resources.pipeline.build.runName)"
    jobs:
      - ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/xtratus') }}:
        - template: image-publish-xtratus.yml
          parameters:
            image_type: 'Ubuntu2204'
            managed_image_name: '$(managed_image_name)'
            agent_pool: 'Xtratus-Tests'
            variable_group_name: 'devops-agents-generation-test'
            azureServiceConnection: 'umi-devops-gl-t-selfhosted-build-01'
            source_managed_image: '/subscriptions/$(ARM_SUBSCRIPTION_ID)/resourceGroups/$(ARM_RESOURCE_GROUP)/providers/Microsoft.Compute/images/$(managed_image_name_full)'

      - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/xtratus') }}:
        - template: image-publish-xtratus.yml
          parameters:
            image_type: 'Ubuntu2204'
            managed_image_name: '$(managed_image_name)'
            agent_pool: 
              name: Xtratus-Managed-Europe
              demands:
                - ImageOverride -equals xtratus-ubuntu-latest
            variable_group_name: 'devops-agents-generation-shared'
            azureServiceConnection: 'umi-devops-gl-a-selfhosted-build-01'
            source_managed_image: '/subscriptions/$(ARM_SUBSCRIPTION_ID)/resourceGroups/$(ARM_RESOURCE_GROUP)/providers/Microsoft.Compute/images/$(managed_image_name_full)'
