trigger: none
pr: none
resources:
  pipelines:
    - pipeline: build
      source: selfhosted_ubuntu_22.04-build
      trigger:
        branches:
          include:
            - xtratus

stages:
  - stage: image_publish
    variables:
      - name: managed_image_name
        value: "SelfHosted_Ubuntu2204"
      - name: managed_image_name_full
        value: "$(managed_image_name)_$(resources.pipeline.build.runName)"
    jobs:
      - template: image-publish-xtratus.yml
        parameters:
          image_type: 'Ubuntu2204'
          managed_image_name: '$(managed_image_name)'
          azureServiceConnection: 'SPN_IA-CORP-CORE-COMMONSERV_SelfhostedBuild'
          source_managed_image: '/subscriptions/$(IMAGE_GALLERY_SUBSCRIPTION_ID)/resourceGroups/$(MANAGED_IMAGE_RESOURCE_GROUP)/providers/Microsoft.Compute/images/$(managed_image_name_full)'
