name: $(Date:yyyyMMdd)$(Rev:.r)
pr: none
trigger:
  branches:
    include:
      - xtratus
      - feature/*
      - feat/*
      - hotfix/*
      - fix/*
    exclude:
      - main
  paths:
    include:
      - images/ubuntu/assets/post-gen/*
      - images/ubuntu/scripts/*      
      - images/ubuntu/assets/ubuntu2204.conf      
      - images/ubuntu/templates/build.ubuntu-22_04.pkr.hcl
      - images/ubuntu/toolsets/toolset-2204.json
      - images/ubuntu/Ubuntu2204-Readme.md

stages:
  - stage: image_generation
    variables:
      - name: managed_image_name
        value: "selfhosted_ubuntu2204"
    jobs:
      - ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/xtratus') }}:
        - template: image-generation-xtratus.yml
          parameters:
            image_type: ubuntu2204
            image_os: ubuntu22
            image_readme_name: Ubuntu2204-Readme.md
            image_template_name: build.ubuntu-22_04.pkr.hcl
            agent_pool: 'Xtratus-Tests'
            variable_group_name: 'devops-agents-generation-test'
            azureServiceConnection: 'umi-devops-gl-t-selfhosted-build-01'

      - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/xtratus') }}:
        - template: image-generation-xtratus.yml
          parameters:
            image_type: ubuntu2204
            image_os: ubuntu22
            image_readme_name: Ubuntu2204-Readme.md
            image_template_name: build.ubuntu-22_04.pkr.hcl
            agent_pool: 
              name: Xtratus-Managed-Europe
              demands:
                - ImageOverride -equals xtratus-ubuntu-latest
            variable_group_name: 'devops-agents-generation-shared'
            azureServiceConnection: 'umi-devops-gl-a-selfhosted-build-01'
