name: $(Date:yyyyMMdd)$(Rev:.r)
pr: none
trigger:
  branches:
    include:
      - xtratus
      - feature/*
      - hotfix/*
    exclude:
      - main
  paths:
    include:
      - images/linux/ubuntu2004.pkr.hcl
      - images/linux/config/ubuntu2004.conf
      - images/linux/post-generation/*
      - images/linux/scripts/*
      - images/linux/toolsets/toolset-2004.json

stages:
  - stage: image_generation
    variables:
      - name: managed_image_name
        value: "selfhosted_ubuntu2004"
    jobs:
      - template: image-generation-xtratus.yml
        parameters:
          image_type: ubuntu2004
          image_readme_name: Ubuntu2004-Readme.md
