# schedules:
# - cron: "0 0 * * *"
#   displayName: Daily
#   branches:
#     include:
#     - main
#   always: true
trigger:
  branches:
    include:
      - main
      - features/*
      - hotfix/*
pr:
  autoCancel: true
  branches:
    include:
      - main

stages:
  - stage: image_generation
    variables:
      - name: managed_image_name
        value: "SelfHosted_Ubuntu1804"
      - name: managed_image_version
        ${{ if in(variables['Build.SourceBranchName'],'main','xtratus')) }}:
          value: "$(MANAGED_IMAGE_ROOT_VERSION)"
        ${{ if notIn(variables['Build.SourceBranchName'],'main','xtratus')) }}:
          value: "$(MANAGED_IMAGE_ROOT_VERSION)-$(Build.BuildNumber)"
    jobs:
      - template: image-generation.yml
        parameters:
          image_type: ubuntu1804
          image_readme_name: Ubuntu1804-Readme.md
          agent_pool: Agent Pool Linux
          variable_group_name: devops-agents-generation-shared
          create_release: false
          repository_ref: "self"
