name: $(Date:yyyyMMdd)$(Rev:.r)
pr: none
trigger:
  branches:
    include:
      - xtratus
      - feature/*
      - hotfix/*
    exclude:
      - main
  paths:
    include:
      - images/linux/ubuntu2204.pkr.hcl
      - images/linux/config/ubuntu2204.conf
      - images/linux/post-generation/*
      - images/linux/scripts/*
      - images/linux/toolsets/toolset-2204.json

stages:
  - stage: image_generation
    variables:
      - name: managed_image_name
        value: "selfhosted_ubuntu2204"
    jobs:
      - template: image-generation-xtratus.yml
        parameters:
          image_type: ubuntu2204
          image_readme_name: Ubuntu2204-Readme.md
          image_template_name: ubuntu-22.04.pkr.hcl
          azureServiceConnection: 'SPN_IA-CORP-CORE-COMMONSERV_SelfhostedBuild'
