trigger: none
pr: none
resources:
  pipelines:
    - pipeline: build
      source: selfhosted_ubuntu_22.04-build
      trigger:
        branches:
          include:
            - xtratus

stages:
  - stage: image_publish
    variables:
      - name: managed_image_name
        value: "SelfHosted_Ubuntu2204"
      - name: managed_image_name_full
        value: "${{ lower(variables.managed_image_name) }}_$(resources.pipeline.build.runName)"
    jobs:
      - template: image-publish-xtratus.yml
        parameters:
          image_type: 'Ubuntu2204'
          managed_image_name: '$(managed_image_name)'
          azureServiceConnection: 'umi-devops-gl-a-selfhosted-build-01'
          source_managed_image: '/subscriptions/$(ARM_SUBSCRIPTION_ID)/resourceGroups/$(ARM_RESOURCE_GROUP)/providers/Microsoft.Compute/images/$(managed_image_name_full)'
