
resources:
  pipelines:
    - pipeline: build
      source: selfhosted_ubuntu_20.04-build
      trigger:
        branches:
          include:
            - xtratus
          
stages:
  - stage: image_publish
    variables:
      - name: library_definition_name
        value: "SelfHosted_Ubuntu2004"
      - name: managed_image_name
        value: "$(managed_image_name)_${{ resources.pipeline.build.runName }}"
    jobs:
      - template: image-publish-xtratus.yml
        parameters:
          image_type: ubuntu2004
          azureServiceConnection: IA-CORP-CORE-COMMONSERV
          source_managed_image: '/subscriptions/$(AZURE_SUBSCRIPTION)/resourceGroups/$(BUILD_RESOURCE_GROUP_NAME)/providers/Microsoft.Compute/images/$(managed_image_name)'
