schedules:
- cron: "0 0 * * *"
  displayName: Daily
  branches:
    include:
    - main
  always: true

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

jobs:
- template: image-generation.yml
  parameters:
    job_id: ubuntu2004_generate_image
    image_type: ubuntu2004
    image_readme_name: Ubuntu2004-Readme.md
    agent_pool: Agent Pool Linux
    variable_group_name: devops-agents-generation-shared
    create_release: true
    repository_ref: 'self'
