trigger: none
pr: none
resources:
  pipelines:
    - pipeline: build
      source: selfhosted_ubuntu_20.04-build
      trigger:
        branches:
          include:
            - xtratus
            - feature/*
            - hotfix/*

stages:
  - stage: image_publish
    variables:
      - name: image_type
        value: "Ubuntu2004"
      - name: managed_image_name
        value: "SelfHosted_$(image_type)_$(resources.pipeline.build.runName)"
    jobs:
      - template: image-publish-xtratus.yml
        parameters:
          image_type: '$(image_type)'
          azureServiceConnection: 'IA-CORP-CORE-COMMONSERV'
          source_managed_image: '/subscriptions/$(AZURE_SUBSCRIPTION)/resourceGroups/$(BUILD_RESOURCE_GROUP_NAME)/providers/Microsoft.Compute/images/$(managed_image_name)'
