name: $(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include:
      - xtratus
      - feature/*
      - hotfix/*
    exclude:
      - main
  paths:
    include:
      - images/win/windows2022.pkr.hcl
      - images/win/post-generation/*
      - images/win/scripts/*
      - images/win/toolsets/toolset-2022.json

stages:
  - stage: image_generation
    variables:
      - name: managed_image_name
        value: "selfhosted_windows2022"
      # - name: managed_image_version
      #   ${{ if in(variables['Build.SourceBranchName'],'main','xtratus') }}:
      #     value: "$(MANAGED_IMAGE_ROOT_VERSION)"
      #   ${{ if notIn(variables['Build.SourceBranchName'],'main','xtratus') }}:
      #     value: "$(MANAGED_IMAGE_ROOT_VERSION)-$(Build.BuildNumber)"
    jobs:
      - template: image-generation-xtratus.yml
        parameters:
          image_type: windows2022
          image_readme_name: Windows2022-Readme.md
