# schedules:
#   - cron: "0 0 * * *"
#     displayName: Daily
#     branches:
#       include:
#         - main
#     always: true
trigger:
  branches:
    include:
    - main
    - features/*
    - hotfix/*
pr:
  autoCancel: true
  branches:
    include:
      - main

jobs:
  - variables:
      - name: managed_image_name
        value: "SelfHosted_Windows2022"
      - name: managed_image_version
        value: "$(MANAGED_IMAGE_ROOT_VERSION)-$(Build.BuildNumber)"

  - template: image-generation.yml
    parameters:
      image_type: Windows2022
      image_readme_name: Windows2022-Readme.md
      agent_pool: Agent Pool Linux
      variable_group_name: devops-agents-generation-shared
      create_release: false
      repository_ref: "self"
