name: $(Date:yyyyMMdd)$(Rev:.r)
pr: none
trigger:
  branches:
    include:
      - xtratus
      - feature/*
      - hotfix/*
      - feat/*
      - fix/*
    exclude:
      - main
  paths:
    include:
      - images/win/windows2022.pkr.hcl
      - images/win/post-generation/*
      - images/win/scripts/*
      - images/win/toolsets/toolset-2022.json

stages:
  - stage: image_generation
    variables:
      - name: managed_image_name
        value: "selfhosted_windows2022"
    jobs:
      - template: image-generation-xtratus.yml
        parameters:
          image_type: windows2022
          image_readme_name: Windows2022-Readme.md
          image_template_name: windows-2022.pkr.hcl
          azureServiceConnection: 'umi-devops-gl-a-selfhosted-build-01'
