name: $(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include:
      - xtratus
      - features/*
      - hotfix/*
    exclude:
      - main
  paths:
    include:
      - images/win/windows2019.pkr.hcl
      - images/win/post-generation/*
      - images/win/scripts/*
      - images/win/toolsets/toolset-2019.json

stages:
  - stage: image_Sgeneration
    variables:
      - name: managed_image_name
        value: "SelfHosted_Windows2019"
      # - name: managed_image_version
      #   ${{ if in(variables['Build.SourceBranchName'],'main','xtratus') }}:
      #     value: "$(MANAGED_IMAGE_ROOT_VERSION)"
      #   ${{ if notIn(variables['Build.SourceBranchName'],'main','xtratus') }}:
      #     value: "$(MANAGED_IMAGE_ROOT_VERSION)-$(Build.BuildNumber)"
    jobs:
      - template: image-generation.yml
        parameters:
          image_type: windows2019
          image_readme_name: Windows2019-Readme.md
          agent_pool: Agent Pool Linux
          variable_group_name: devops-agents-generation-shared
          create_release: false
          repository_ref: "self"
