# schedules:
#   - cron: "0 0 * * *"
#     displayName: Daily
#     branches:
#       include:
#         - main
#     always: true
trigger:
  branches:
    include:
      - main
      - features/*
      - hotfix/*
  paths:
    include:
      - images/win/windows2022.pkr.hcl
      - images/win/post-generation/*
      - images/win/scripts/*
      - images/win/toolsets/toolset-2022.json
      
pr:
  autoCancel: true
  branches:
    include:
      - main

stages:
  - stage: image_generation
    variables:
      - name: managed_image_name
        value: "SelfHosted_Windows2022"
      - name: managed_image_version
        ${{ if in(variables['Build.SourceBranchName'],'main','xtratus') }}:
          value: "$(MANAGED_IMAGE_ROOT_VERSION)"
        ${{ if notIn(variables['Build.SourceBranchName'],'main','xtratus') }}:
          value: "$(MANAGED_IMAGE_ROOT_VERSION)-$(Build.BuildNumber)"
    jobs:
      - template: image-generation.yml
        parameters:
          image_type: windows2022
          image_readme_name: Windows2022-Readme.md
          agent_pool: Agent Pool Linux
          variable_group_name: devops-agents-generation-shared
          create_release: false
          repository_ref: "self"
