name: $(Date:yyyyMMdd)$(Rev:.r)
pr: none
trigger:
  branches:
    include:
      - xtratus
      - feature/*
      - hotfix/*
    exclude:
      - main
  paths:
    include:
      - images/win/windows2019.pkr.hcl
      - images/win/post-generation/*
      - images/win/scripts/*
      - images/win/toolsets/toolset-2019.json

stages:
  - stage: image_Sgeneration
    variables:
      - name: managed_image_name
        value: "selfhosted_windows2019"
    jobs:
      - template: image-generation-xtratus.yml
        parameters:
          image_type: windows2019
          image_readme_name: Windows2019-Readme.md
